import asyncio
from datetime import UTC, datetime
from typing import Literal

import structlog
from redis.asyncio import Redis

from aether.agents.base import AgentContext
from aether.core.events import EventBus
from aether.llm._models import Message
from aether.memory.api import MemoryAPI

from .models import Session, SessionContext, SessionMode
from .startup import SessionStartupBuilder

logger = structlog.get_logger(__name__)


class SessionManager:
    """Manages the lifecycle of an interaction session.

    All conversation persistence flows through MemoryAPI's public
    conversation accessors (M2.1.5 boundary correction) — this class holds
    no database session factory and no direct consolidation pipeline.
    """

    SESSION_CONTEXT_TTL_SECONDS: int = 86400  # 24 hours

    def __init__(
        self,
        startup_builder: SessionStartupBuilder,
        memory_api: MemoryAPI,
        event_bus: EventBus,
        redis_client: Redis,
    ):
        self._startup_builder = startup_builder
        self._memory_api = memory_api
        self._event_bus = event_bus
        self._redis = redis_client

    def _cache_key(self, session_id: str) -> str:
        return f"aether:session:{session_id}:context"

    async def start_session(self, mode: SessionMode = SessionMode.TEXT) -> Session:
        """Starts a new session, caches context, and emits event."""
        now = datetime.now(UTC)

        # 1. Create the conversation record through the Memory API — the
        # session id IS the conversation id, generated by the store.
        session_id = await self._memory_api.start_conversation(mode.value)

        # 2. Build context
        context = await self._startup_builder.build_context(session_id)

        # 3. Cache SessionContext in Redis
        # model_dump_json handles the serialization securely (no pickle)
        await self._redis.set(
            self._cache_key(session_id),
            context.model_dump_json(),
            ex=self.SESSION_CONTEXT_TTL_SECONDS,
        )

        # 4. Emit session.lifecycle.started
        await self._event_bus.emit(
            event_type="session.lifecycle.started",
            payload={"mode": mode.value},
            session_id=session_id,
            correlation_id=session_id,
            source="aether.session",
        )

        return Session(
            id=session_id,
            started_at=now,
            mode=mode,
            status="active",
            message_count=0,
        )

    async def end_session(
        self, session_id: str, trigger: Literal["user", "timeout", "system"] = "user"
    ) -> None:
        """Ends the session and triggers non-blocking consolidation."""
        # 1. Close the conversation record through the Memory API (sets
        # ended_at and computes the true message_count from persisted rows).
        await self._memory_api.end_conversation(session_id)

        # 2. Emit session.lifecycle.ended
        await self._event_bus.emit(
            event_type="session.lifecycle.ended",
            payload={"trigger": trigger},
            session_id=session_id,
            correlation_id=session_id,
            source="aether.session",
        )

        # 3. Trigger consolidation (NON-BLOCKING)
        asyncio.create_task(self._consolidate_in_background(session_id))

        # 4. Delete Redis session cache key
        await self._redis.delete(self._cache_key(session_id))

    async def get_context(self, session_id: str) -> SessionContext:
        """Retrieves session context from Redis or rebuilds it if missing."""
        cached_data = await self._redis.get(self._cache_key(session_id))

        if cached_data:
            # 2. Deserialize and return
            return SessionContext.model_validate_json(cached_data)

        # 3. Cache miss: rebuild from SQLite + startup_builder
        logger.info("Session context cache miss, rebuilding", session_id=session_id)

        # Load from DB to check message_count (simplified rebuild logic here just calls build_context)
        # Realistically, you would also load past messages here, but we will just rely on startup_builder
        # to re-fetch the base context.
        rebuilt_context = await self._startup_builder.build_context(session_id)

        # 4. Re-cache the rebuilt context
        await self._redis.set(
            self._cache_key(session_id),
            rebuilt_context.model_dump_json(),
            ex=self.SESSION_CONTEXT_TTL_SECONDS,
        )

        return rebuilt_context

    async def update_context(self, session_id: str, new_messages: list[Message]) -> None:
        """Updates the session context with new messages."""
        context = await self.get_context(session_id)

        updated_messages = list(context.messages) + new_messages

        updated_context = SessionContext(
            session_id=context.session_id,
            messages=updated_messages,
            active_tasks=context.active_tasks,
            memory_context=context.memory_context,
            working_summary=context.working_summary,
            last_activity=datetime.now(UTC),
        )

        # Re-serialize and store back to Redis with same TTL
        await self._redis.set(
            self._cache_key(session_id),
            updated_context.model_dump_json(),
            ex=self.SESSION_CONTEXT_TTL_SECONDS,
        )

        # Persist each new turn through the Memory API. This replaces the old
        # raw message_count increment: rows are now actually stored, and
        # end_conversation() derives the count from them, so consolidation
        # finally has a real transcript to read.
        for message in new_messages:
            await self._memory_api.record_message(
                conversation_id=session_id,
                role=message.role,
                content=message.content,
            )

    async def build_agent_context(self, session_id: str, user_input: str) -> AgentContext:
        """The single shared point where a cached SessionContext becomes an AgentContext.

        Any interface dispatching to AgentRuntime must go through this method
        rather than assembling AgentContext by hand (M2.1.6). The current
        user input is appended as the final user Message of
        conversation_history — ConversationAgent reads the turn's input from
        the history it already consumes — and is also used as the memory
        recall query.

        Args:
            session_id: The active session whose context to assemble.
            user_input: The user's message for this conversational turn.

        Returns:
            A frozen AgentContext ready for AgentRuntime.execute().
        """
        context = await self.get_context(session_id)
        memory_context = await self._memory_api.recall(user_input)
        return AgentContext(
            session_id=session_id,
            conversation_history=[
                *context.messages,
                Message(role="user", content=user_input),
            ],
            memory_context=memory_context,
            active_tasks=context.active_tasks,
            system_state={},
        )

    async def get_morning_briefing(self, session_id: str) -> str:
        """Delegates to startup_builder.build_morning_briefing(context)."""
        context = await self.get_context(session_id)
        return await self._startup_builder.build_morning_briefing(context)

    async def _consolidate_in_background(self, session_id: str) -> None:
        """Background task — NEVER awaited from end_session()"""
        try:
            await self._memory_api.consolidate(session_id)
        except Exception as e:
            logger.error("session.consolidation.failed", session_id=session_id, error=str(e))
            # Do NOT re-raise — consolidation failure must not propagate
